### PR TITLE
KZOO-410: UUID treatment for command selector

### PR DESCRIPTION
**Pull request by kdamas93**
Is necessary implement/automate the use of UUID for the command selector for its _id.
To do this, it is necessary to receive the uuid field in the payload through the console and in the URL from the API and this will be validated and stored in the _id and uuid fields documents.

### CODE REVIEW

**Comment by Navoda626** [comment]
Changes looks good to me. @kdamas93 its better to change the PR heading to proper format

**Review by icehess — APPROVED** [review]

**Comment by icehess** [comment]
related prs

- master:
    - https://github.com/2600hz/kazoo-core/pull/721
    - https://github.com/2600hz/kazoo-crossbar/pull/516
    - https://github.com/2600hz/kazoo-properly/pull/177
- 5.3 :
    - https://github.com/2600hz/kazoo-core/pull/723
    - https://github.com/2600hz/kazoo-properly/pull/178
    - https://github.com/2600hz/kazoo-crossbar/pull/517

**Comment by icehess** [comment]
@kdamas93 In the future please link all related PRs in the comment!

**Comment by kdamas93** [comment]
> @kdamas93 In the future please link all related PRs in the comment!

got it @icehess , thanks !

**Pull request merged**
