### PR TITLE
KZOO-385: return Default if value at Key is 'undefined'

### PR DESCRIPTION
**Pull request by jamesaimonetti**

### CODE REVIEW

**Comment by jamesaimonetti** [comment]
```
(k5-priv@compy64.2600hz.com)3> Call0 = kapps_call:new().
{kapps_call,undefined,#Fun<kapps_call.3.59765155>,undefined,
            undefined,undefined,#Fun<kapps_call.3.59765155>,undefined,
            undefined,undefined,undefined,undefined,<<>>,undefined,
            undefined,undefined,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,undefined,undefined,undefined,undefined,...}
(k5-priv@compy64.2600hz.com)4> Props = [{'cf_capture_group', 'undefined'}].
[{cf_capture_group,undefined}]
(k5-priv@compy64.2600hz.com)5> Call1 = kapps_call:kvs_store_proplist(Props, Call0).
{kapps_call,undefined,#Fun<kapps_call.3.59765155>,undefined,
            undefined,undefined,#Fun<kapps_call.3.59765155>,undefined,
            undefined,undefined,undefined,undefined,<<>>,undefined,
            undefined,undefined,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,<<"nouser@norealm">>,<<"nouser">>,
            <<"norealm">>,undefined,undefined,undefined,undefined,...}
(k5-priv@compy64.2600hz.com)6> kapps_call:kvs_fetch('cf_capture_group', <<>>, Call1).
undefined
```

Expectation would be to get `<<>>` here instead

**Comment by lazedo** [comment]
@jamesaimonetti makes sense but i wouldn't expect to see `[{'cf_capture_group', 'undefined'}]` stored. maybe that part needs checking/fixing

**Comment by pavel-farkas** [comment]
Checked with the example above and it returns <<>> after proposed change.

**Review by pavel-farkas — APPROVED** [review]
Works as expected

**Comment by jamesaimonetti** [comment]
@lazedo yes am checking into that as well; this seemed like a good change to avoid surprises like above.

**Pull request merged**
