### PR TITLE
KCRO-189: Config migration from crossbar to desktop

### PR DESCRIPTION
**Pull request by Navoda626**
Config migration from crossbar to desktop, exporting migrate_config_setting/1 function to call from desktop_app.erl module.

Previously, kapps_config:migrate_config_setting/1 was not exported.

Now, kapps_config:migrate_config_setting/1 is exported to be used in config migration in desktop_app.erl module.

### CODE REVIEW

**Comment by manushiperera** [comment]
Hello @Navoda626, can you please update the PR summary with related PR ( https://github.com/2600hz/kazoo-desktop/pull/31)?
Further can you please use the PR summary format (previously,... now,...) which is recommended by James?
Thanks

**Comment by manushiperera** [comment]
#714 PR changes are matching with #715

**Comment by Navoda626** [comment]
Hello @manushiperera, PR description is updated. 

And from the 2 PRs https://github.com/2600hz/kazoo-desktop/pull/31 and https://github.com/2600hz/kazoo-core/pull/714 desktop PR is the major one and there I mentioned https://github.com/2600hz/kazoo-core/pull/714 as a required PR. Is it required to mention the major PR link as a related PR in the minor PRs?

**Comment by manushiperera** [comment]
Thanks @Navoda626. In my point of view, if someone is looking into minor PR, he/she cannot find other related PRs.

**Comment by Navoda626** [comment]
@manushiperera I think when we mention a PR link, that linked PR will get a log like `mentioned this pull request`. But I'm not sure if that is sufficient

**Comment by manushiperera** [comment]
Sorry, I did not notice that log. I guess, it is sufficient. 
Thanks.

**Pull request merged**
