### PR TITLE
KCRO-168: Validating the getstream feature enabled in user document

### PR DESCRIPTION
**Pull request by Navoda626**
KCRO-168: Validating the getstream feature enabled in user document

Earlier when the getstream API PUT /accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream/connect is called user is connected to getstream API without validating whether the user has getstream feature (chat.getstream.emabled=true).

Now, added chat.getstream.emabled parameter is the user document schema in crossbar and in core added kzd functions related to chat parameters

### CODE REVIEW

**Comment by nkarunarathne** [comment]
Changes look good

**Review by lazedo — CHANGES_REQUESTED** [review]
why are these being added here ?
kzd_users should not have app specifics
maybe add a kzd_chat and kzd_getstream each dealing with properties of their domain

**Comment by Navoda626** [comment]
> why are these being added here ? kzd_users should not have app specifics maybe add a kzd_chat and kzd_getstream each dealing with properties of their domain

@lazedo This chat.getstream.enabled parameter is added to the user document schema as a feature that a user has. Is it still  need to be moved to other module?

**Comment by Navoda626** [comment]
Accessor functions are moved to a kzd_chat.erl module since they are application specific parameters

**Comment by Navoda626** [comment]
Moved the required accessor functions to cb_getstream.erl module. So closing this PR

**Pull request closed without merging**
