### PR TITLE
KCRO-29: add kapi for kapi_registrations:search_req

### PR DESCRIPTION
**Pull request by icehess**

### CODE REVIEW

**Comment by lazedo** [comment]
@icehess looks good so far, but it how do you handle the `partial_resp` for `detail` requests ?

**Comment by icehess** [comment]
> @icehess looks good so far, but it how do you handle the `partial_resp` for `detail` requests ?

Isn't kamailio terminates partial response with a `search_resp` message?

**Comment by lazedo** [comment]
but you need to collect them

**Comment by lazedo** [comment]
@icehess check this for reference https://github.com/2600hz/kazoo-crossbar/blob/master/src/modules/cb_presence.erl#L210-L230

**Pull request merged**
